definitions:
  audionflow.FlowRequest:
    properties:
      folderId:
        description: Folder ID
        example: my-folder
        type: string
      input:
        description: Input
        example: media path or youtube url
        type: string
      inputType:
        description: Input Type
        example: url
        type: string
    required:
    - folderId
    - input
    - inputType
    type: object
  msg.Response:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
host: api.magovoice.com/audion
info:
  contact:
    email: contact@holamago.com
    name: Galois
  description: Audion Flow API - /v1/go/flow endpoints only
  title: Audion Flow API
  version: "1.0"
paths:
  /v1/go/flow:
    post:
      consumes:
      - multipart/form-data
      description: 'Executes a flow for a specific project using API key authentication.
        Use Authorization header with format: "Bearer {API_KEY}"'
      parameters:
      - description: Bearer {API_KEY} - API key authentication header
        format: bearer
        in: header
        name: Authorization
        required: true
        type: string
      - description: 'Flow name: audion-vu, audion-vh'
        in: formData
        name: flow
        required: true
        type: string
      - description: Input type (file, url, youtube, etc.)
        in: formData
        name: input_type
        required: true
        type: string
      - description: Input data (path/url)
        in: formData
        name: input
        type: string
      - description: Input file (for file input type)
        in: formData
        name: input
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Flow executed successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/msg.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/msg.Response'
        "404":
          description: Project not found
          schema:
            $ref: '#/definitions/msg.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/msg.Response'
      security:
      - ApiKeyAuth: []
      summary: Run flow with API key authentication
      tags:
      - API Flow

securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
schemes:
- https
- http
swagger: "2.0"